#******************************************************************************************************************
# File: docker-compose-base.yaml
# Project: MSIT-SE Studio Project (Data61)
# Copyright: Team Unchained
# Versions:
#   1.0 March 2018 - Modified based on a sample file (Dongliang Zhou)
#   2.0 May 2018 - Transformed into a template for autogeneration (Dongliang Zhou)
#
# Description: This is the template base file defining docker containers to simulate testing network.
#
# External Dependencies: Hyperledger fabric library
#
#*****************************************************************************************************************/

# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.${domain}:
    container_name: orderer.${domain}
    image: hyperledger/fabric-orderer:\$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/${domain}/orderers/orderer.${domain}/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/${domain}/orderers/orderer.${domain}/tls/:/var/hyperledger/orderer/tls
    - orderer.${domain}:/var/hyperledger/production/orderer
    ports:
      - ${ordererPort}:7050
# docker-compose-base-peer.yaml content goes here
