  ${peerDomainPrefix}_cli:
    container_name: ${peerDomainPrefix}_cli
    image: hyperledger/fabric-tools:\$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=${peerDomainPrefix}_cli
      - CORE_PEER_ADDRESS=peer0.${peerDomainPrefix}.${domain}:7051
      - CORE_PEER_LOCALMSPID=${peerName}MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${peerDomainPrefix}.${domain}/peers/peer0.${peerDomainPrefix}.${domain}/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${peerDomainPrefix}.${domain}/peers/peer0.${peerDomainPrefix}.${domain}/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${peerDomainPrefix}.${domain}/peers/peer0.${peerDomainPrefix}.${domain}/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/${peerDomainPrefix}.${domain}/users/Admin@${peerDomainPrefix}.${domain}/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.${domain}
# docker-compose-cli-depends-on.yaml content goes here
${cliDependsOn}
    networks:
      - ${networkName}